language: java
jdk: oraclejdk7
before_install:
  # Install base Android SDK
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
    - export COMPONENTS=build-tools-19.0.1,android-19,sysimg-16,extra-android-support

    # Create and start emulator
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - wait_for_emulator

script: ./gradlew connectedInstrumentTest
